# Generated by Django 5.2.8 on 2025-12-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Customer',
            new_name='customer',
        ),
    ]
